version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0.21
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
    restart: always

volumes:
  mosquitto-data:
